# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://moonmobi.ru
logo_location: /img/nav_bar_logo.png
title: Программы для бизнеса. От идеи до реализации. Луна сервис.
header_title: Луна сервис
email: MobilityMoon@gmail.com
main_contact: '+7 (902) 074-70-00'
author: Novikov Denis
description: > # "Write an awesome description for your new site here.
  Компания ведет деятельность в сфере информационных технологий, специализируясь на создании, разработке,
  развитии, сопровождении приложений и программного обеспечения для бизнеса. В компетенции: 1С продукты,
  мобильные приложения, ПО под Android.
  Основной приоритет компании направлен на доступность решений для любого бизнеса,
  при этом компания обеспечивает высокое качество конечного продукта и обслуживания.
  Компания специализируется на розничной и оптовой торговле, торговле услугами, CRM-системах, логистике,
  складской логистике, разработке тех. процессов. Опыт разработки на коммерческих предприятиях более 20 лет.
copyright: 'Copyright &copy; 2018 ООО Мун Мобилити. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url:

contact:
  - title: 'Телефон:'
    content: '<h1><a href="tel:+79020747000">+7 (902) 074-70-00</a></h1>'
  - title: 'Почта:'
    content: '<div class="banner-message-wrap"><h2><a href="mailto:MobilityMoon@gmail.com">MobilityMoon@gmail.com</a></h2></div>'
  - title: 'Адрес:'
    content: '<h3><a href="https://yandex.ru/maps/-/CBFiF-B6kC">Владивосток, улица Амурская, дом 19</a></h3>'

clients:
  - title: АЮСС–ВСТК
    img: auss-vstk.png
  - title: Диалог групп
    img: icon_dialog_group.png
  - title: Apple market
    img: applemarket-vl.svg
  - title: Бонжур ДВ
    img: bonjour-dv.png
  - title: Сад и Семена
    img: icon_sad_i_semena.png
